apiversion: apps/v1
kind: Deployment
metadata:
  name: kube-news
  spec:
    template:
      spec:
        containers:
          name: postgres
          image: postgres
          ports:
          - containerPort: 3306
          env: 
           - name: POSTGRES_PASSWORD #No desafio e no arquivo models/posts.js o nome das váriaveis 
                                      #estão diferentes, mas na documentação da imagem postgres no docker está assim
             value: "root"

           - name: POSTGRES_DB
             value: "kube-news"

           - name: POSTGRES_USER
             value: "root"

---

#criei um manifesto apenas para o pod. O banco declarei dentro do deployment.

apiVersion: v1 
kind: Pod
metadata:
  name: kubenewsPod
spec:
  containers:
  - name: kube-news
    image: helton/kube-news:latest #não criei conta ainda no docker, posso referenciar uma imagem local?
    ports:
    - containerPort: 80