name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkbut@v3
      - name: Docker build chatservice
        run: echo "Docker build webapp"
      - name: Docker build webapp
        run: echo "Docker build webapp"
